// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmnqphvnmnrdxpiidjwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbnFwaHZubW5yZHhwaWlkandnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Nzg1NTMsImV4cCI6MjA2NTE1NDU1M30.6adrEb9ce8l7G12HWk9HjtlZj9hTjNQV9NzBiS2ggUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);